name: Run Bot Script

on:
  schedule:
    - cron: '0 8-23 * * *'  # Run every hour from 8:00 AM to 11:00 PM (midnight)
  workflow_dispatch:  # Allow manual runs

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Restore cached dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies (if cache is empty or outdated)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot script
        run: python bot.py  # Ensure bot.py is at the root of your repo

      - name: Update Website with Latest Changes
        run: |
          git config --global user.name 'ClashMasterRaghav'
          git config --global user.email 'gamescocclans123@gmail.com'
          git add .
          git commit -m "Update website with latest IPO data"
          git push origin main

      - name: Stage and Commit Changes
        run: |
          git config --global user.name 'ClashMasterRaghav'
          git config --global user.email 'gamescocclans123@gmail.com'
          git add ipo_data.csv
          git commit -m "Intermediate commit for rebase"

      - name: Add and Commit Changes
        run: |
          git add .
          if git diff-index --quiet HEAD; then
            echo "Nothing to commit. Skipping commit step."
          else
            git commit -m "Automated commit"
          fi
          
      - name: Pull and Push Changes
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/ClashMasterRaghav/prrintmoney.com.git
          git pull origin main --rebase  # Pull new changes to avoid conflicts
          git push origin main  # Push the final changes

      - name: Debug Git State
        run: |
          git status
          git log -1
          ls -l

      - name: Upload IPO data CSV
        uses: actions/upload-artifact@v3
        with:
          name: ipo-data
          path: ipo_data.csv
