name: Run Bot Script

on:
  schedule:
    - cron: '0 * * * *'  # Run every 1 hour
  workflow_dispatch:  # Allow manual runs

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Restore cached dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies (if cache is empty or outdated)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot script
        run: python bot.py  # Ensure bot.py is at the root of your repo

      - name: Upload IPO data CSV
        uses: actions/upload-artifact@v3
        with:
          name: ipo-data
          path: ipo_data.csv
