name: Run Bot Script

on:
  schedule:
    - cron: '30 2-17 * * *'  # Run every hour from 8:00 AM to 11:00 PM IST
  workflow_dispatch:  # Allow manual runs

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Restore cached dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot script
        run: python bot.py  # Ensure bot.py is at the root of your repo

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'ClashMasterRaghav'
          git config --global user.email 'gamescocclans123@gmail.com'
          git add .
          git diff --quiet || (git commit -m "Update website and IPO data" &&
          git pull origin main --rebase &&
          git push origin main)

      - name: Debug Git State
        run: |
          git status
          git log -1
          ls -l

      - name: Upload IPO Data as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ipo-data
          path: ipo_data.csv
