name: Update Pages

on:
  workflow_run:
    workflows: ["Run Bot Script"]
    types:
      - completed  # Trigger this workflow after the bot script completes

jobs:
  update-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and Deploy Pages
        run: |
          # Add your website build or update commands here
          # For example:
          python generate_pages.py  # If you use a script to generate the site
          git config --global user.name 'ClashMasterRaghav'
          git config --global user.email 'gamescocclans123@gmail.com'
          git add .
          git commit -m "Update website with latest IPO data"
          git push origin main
